---
- name: Brew taps
  community.general.homebrew_tap:
    name:
      - homebrew/cask-fonts
      - amar1729/formulae

- name: Desktop Packages
  community.general.homebrew:
    name: '{{ item }}'
  ignore_errors: yes
  with_items:
    - font-iosevka-nerd-font
    - font-noto-sans
    - obs
    - audacity
    - browserpass
    - mpv
    - firefox
    - alacritty
    - rectangle
    - icanhazshortcut
    - gimp
    - utm

- name: Configure browserpass for Chrome
  shell: PREFIX=$(brew --prefix) make hosts-chrome-user -f "$(brew --prefix)/lib/browserpass/Makefile"

- name: Install browserpass Chrome extension
  shell: PREFIX=$(brew --prefix) make policies-chrome -f "$(brew --prefix)/lib/browserpass/Makefile"
  become: true

- name: Configure browserpass for Firefox
  shell: PREFIX=$(brew --prefix) make hosts-firefox-user -f "$(brew --prefix)/lib/browserpass/Makefile"
