---
- name: Fetching dot-files
  git:
    repo: git@github.com:vinikira/dot-files.git
    dest: /Users/{{ lookup('env', 'USER') }}/git/github/vinikira/dot-files
    update: no

- name: Fetching Summon
  git:
    repo: https://gitlab.com/semente/summon
    dest: /Users/{{ lookup('env', 'USER') }}/git/gitlab/semente/summon

- name: Given access to summon
  file:
    path: /Users/{{ lookup('env', 'USER') }}/git/gitlab/semente/summon/summon.sh
    mode: 0755

- name: Make .local directories
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - /Users/{{ lookup('env', 'USER') }}/.local/bin
    - /Users/{{ lookup('env', 'USER') }}/.local/opt

- name: Create link summon
  file:
    src: /Users/{{ lookup('env', 'USER') }}/git/gitlab/semente/summon/summon.sh
    dest: /Users/{{ lookup('env', 'USER') }}/.local/bin/summon.sh
    state: link

- name: Summoning dot-files
  shell: bash /Users/{{ lookup('env', 'USER') }}/.local/bin/summon.sh /Users/{{ lookup('env', 'USER') }}/git/github/vinikira/dot-files/common/{{ item }}
  with_items:
    - zsh
    - bin
    - gpg
    - git
    - htop
    - mail
    - tmux
