---
- name: Fetching dot-files
  git:
    repo: git@github.com:vinikira/dot-files.git
    dest: /Users/{{ lookup('env', 'USER') }}/git/github.com/vinikira/dot-files
    update: no

- name: Make .local directories
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - /Users/{{ lookup('env', 'USER') }}/.local/bin
    - /Users/{{ lookup('env', 'USER') }}/.local/opt

- name: Linking dot-files
  shell: make dotfiles workspace=common/{{ item }}
  args:
    chdir: /Users/{{ lookup('env', 'USER') }}/git/github.com/vinikira/dot-files
  ignore_errors: true
  with_items:
    - zsh
    - bin
    - gpg
    - git
    - htop
    - mail
    - tmux
