---
- name: Added homebrew tap with pre-built emacs gcc release
  community.general.homebrew_tap:
    name: jimeh/emacs-builds

- name: Install Emacs GCC package
  community.general.homebrew_cask:
    name: jimeh/emacs-builds/emacs-app
    state: present
  ignore_errors: true

- name: Trust emacs
  shell: spctl -vvv --assess --type exec /Applications/Emacs.app

- name: Enable Emacs daemon
  tags: emacs
  block:
    - name: copy plist file
      copy:
        src: '../files/gnu.emacs.daemon.plist'
        dest: "/Users/{{ lookup('env', 'USER') }}/Library/LaunchAgents/"

    - name: enalbe service
      shell: launchctl load -w ~/Library/LaunchAgents/gnu.emacs.daemon.plist

- name: Linking Emacs config
  ignore_errors: true
  shell: make dotfiles workspace=common/emacs
  args:
    chdir: /Users/{{ lookup('env', 'USER') }}/git/github.com/vinikira/dot-files

- name: Making Emacs config
  shell: make -k
  args:
    chdir: /Users/{{ lookup('env', 'USER') }}/.emacs.d
  ignore_errors: true
