---
- name: CLI Packages
  community.general.homebrew:
    name:
      - tmux
      - pass
      - bat
      - wget
      - htop
      - aspell
      - ripgrep
      - fd
      - pandoc
      - gpg
      - autoconf
      - openssl
      - wxmac
      - jq
      - libxml2
      - cmake
      - pgformatter
      - pgcli
      - cmake
      - ncspot
      - libpq
    state: present

- name: Cask Packages
  community.general.homebrew_cask:
    name: '{{ item }}'
    state: present
  ignore_errors: yes
  with_items:
    - mactex-no-gui

- include_tasks: asdf.yml
- include_tasks: docker.yml
# broken by summon
# - include_tasks: dot-files.yml
- include_tasks: elixir.yml
- include_tasks: emacs.yml
- include_tasks: syncthing.yml
- include_tasks: vault.yml
- include_tasks: zsh.yml
